/* automatically generated by rust-bindgen */

// Generated using:
// bindgen 0.51.0
// macOS SDK 10.14.

use core_foundation_sys::dictionary::CFDictionaryRef;
use core_foundation_sys::string::{CFStringEncoding, CFStringRef};
use dynamic_store::SCDynamicStoreRef;

pub type __uint32_t = ::libc::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_uid_t = __uint32_t;
pub type gid_t = __darwin_gid_t;
pub type uid_t = __darwin_uid_t;
pub type UInt32 = ::libc::c_uint;
extern "C" {
    pub fn SCDynamicStoreCopyComputerName(
        store: SCDynamicStoreRef,
        nameEncoding: *mut CFStringEncoding,
    ) -> CFStringRef;
}
extern "C" {
    pub fn SCDynamicStoreCopyConsoleUser(
        store: SCDynamicStoreRef,
        uid: *mut uid_t,
        gid: *mut gid_t,
    ) -> CFStringRef;
}
extern "C" {
    pub fn SCDynamicStoreCopyLocalHostName(store: SCDynamicStoreRef) -> CFStringRef;
}
extern "C" {
    pub fn SCDynamicStoreCopyLocation(store: SCDynamicStoreRef) -> CFStringRef;
}
extern "C" {
    pub fn SCDynamicStoreCopyProxies(store: SCDynamicStoreRef) -> CFDictionaryRef;
}
