/* automatically generated by rust-bindgen 0.69.4 */

// Generated using:
// bindgen 0.69.4
// macOS SDK 14.5.

use core_foundation_sys::base::CFAllocatorRef;
use core_foundation_sys::string::CFStringRef;

extern "C" {
    pub fn SCDynamicStoreKeyCreate(allocator: CFAllocatorRef, fmt: CFStringRef, ...)
        -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateNetworkGlobalEntity(
        allocator: CFAllocatorRef,
        domain: CFStringRef,
        entity: CFStringRef,
    ) -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateNetworkInterface(
        allocator: CFAllocatorRef,
        domain: CFStringRef,
    ) -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateNetworkInterfaceEntity(
        allocator: CFAllocatorRef,
        domain: CFStringRef,
        ifname: CFStringRef,
        entity: CFStringRef,
    ) -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateNetworkServiceEntity(
        allocator: CFAllocatorRef,
        domain: CFStringRef,
        serviceID: CFStringRef,
        entity: CFStringRef,
    ) -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateComputerName(allocator: CFAllocatorRef) -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateConsoleUser(allocator: CFAllocatorRef) -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateHostNames(allocator: CFAllocatorRef) -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateLocation(allocator: CFAllocatorRef) -> CFStringRef;

    pub fn SCDynamicStoreKeyCreateProxies(allocator: CFAllocatorRef) -> CFStringRef;
}
