/* automatically generated by rust-bindgen 0.70.1 */

// Generated using:
// bindgen 0.70.1
// macOS SDK 14.5.

use core_foundation_sys::base::Boolean;
use core_foundation_sys::dictionary::CFDictionaryRef;
use core_foundation_sys::string::CFStringRef;

use crate::preferences::SCPreferencesRef;

extern "C" {
    pub fn SCPreferencesPathCreateUniqueChild(
        prefs: SCPreferencesRef,
        prefix: CFStringRef,
    ) -> CFStringRef;

    pub fn SCPreferencesPathGetValue(prefs: SCPreferencesRef, path: CFStringRef)
        -> CFDictionaryRef;

    pub fn SCPreferencesPathGetLink(prefs: SCPreferencesRef, path: CFStringRef) -> CFStringRef;

    pub fn SCPreferencesPathSetValue(
        prefs: SCPreferencesRef,
        path: CFStringRef,
        value: CFDictionaryRef,
    ) -> Boolean;

    pub fn SCPreferencesPathSetLink(
        prefs: SCPreferencesRef,
        path: CFStringRef,
        link: CFStringRef,
    ) -> Boolean;

    pub fn SCPreferencesPathRemoveValue(prefs: SCPreferencesRef, path: CFStringRef) -> Boolean;
}
