// automatically generated by rust-bindgen

// Generated using:
// bindgen 0.42.2
// macOS SDK 10.14.

use core_foundation_sys::string::CFStringRef;


extern "C" {
    #[link_name = "\u{1}_kSCResvLink"]
    pub static mut kSCResvLink: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCResvInactive"]
    pub static mut kSCResvInactive: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropInterfaceName"]
    pub static mut kSCPropInterfaceName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropMACAddress"]
    pub static mut kSCPropMACAddress: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropUserDefinedName"]
    pub static mut kSCPropUserDefinedName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropVersion"]
    pub static mut kSCPropVersion: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPrefCurrentSet"]
    pub static mut kSCPrefCurrentSet: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPrefNetworkServices"]
    pub static mut kSCPrefNetworkServices: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPrefSets"]
    pub static mut kSCPrefSets: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPrefSystem"]
    pub static mut kSCPrefSystem: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCCompNetwork"]
    pub static mut kSCCompNetwork: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCCompService"]
    pub static mut kSCCompService: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCCompGlobal"]
    pub static mut kSCCompGlobal: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCCompHostNames"]
    pub static mut kSCCompHostNames: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCCompInterface"]
    pub static mut kSCCompInterface: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCCompSystem"]
    pub static mut kSCCompSystem: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCCompUsers"]
    pub static mut kSCCompUsers: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCCompAnyRegex"]
    pub static mut kSCCompAnyRegex: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetAirPort"]
    pub static mut kSCEntNetAirPort: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetDHCP"]
    pub static mut kSCEntNetDHCP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetDNS"]
    pub static mut kSCEntNetDNS: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetEthernet"]
    pub static mut kSCEntNetEthernet: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetFireWire"]
    pub static mut kSCEntNetFireWire: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetInterface"]
    pub static mut kSCEntNetInterface: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetIPSec"]
    pub static mut kSCEntNetIPSec: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetIPv4"]
    pub static mut kSCEntNetIPv4: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetIPv6"]
    pub static mut kSCEntNetIPv6: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetL2TP"]
    pub static mut kSCEntNetL2TP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetLink"]
    pub static mut kSCEntNetLink: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetModem"]
    pub static mut kSCEntNetModem: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetPPP"]
    pub static mut kSCEntNetPPP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetPPPoE"]
    pub static mut kSCEntNetPPPoE: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetPPPSerial"]
    pub static mut kSCEntNetPPPSerial: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetPPTP"]
    pub static mut kSCEntNetPPTP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetProxies"]
    pub static mut kSCEntNetProxies: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNetSMB"]
    pub static mut kSCEntNetSMB: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntNet6to4"]
    pub static mut kSCEntNet6to4: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetOverridePrimary"]
    pub static mut kSCPropNetOverridePrimary: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetServiceOrder"]
    pub static mut kSCPropNetServiceOrder: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPOverridePrimary"]
    pub static mut kSCPropNetPPPOverridePrimary: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetInterfaces"]
    pub static mut kSCPropNetInterfaces: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetLocalHostName"]
    pub static mut kSCPropNetLocalHostName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetAirPortAllowNetCreation"]
    pub static mut kSCPropNetAirPortAllowNetCreation: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetAirPortAuthPassword"]
    pub static mut kSCPropNetAirPortAuthPassword: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetAirPortAuthPasswordEncryption"]
    pub static mut kSCPropNetAirPortAuthPasswordEncryption: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetAirPortJoinMode"]
    pub static mut kSCPropNetAirPortJoinMode: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetAirPortPowerEnabled"]
    pub static mut kSCPropNetAirPortPowerEnabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetAirPortPreferredNetwork"]
    pub static mut kSCPropNetAirPortPreferredNetwork: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetAirPortSavePasswords"]
    pub static mut kSCPropNetAirPortSavePasswords: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetAirPortJoinModeAutomatic"]
    pub static mut kSCValNetAirPortJoinModeAutomatic: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetAirPortJoinModePreferred"]
    pub static mut kSCValNetAirPortJoinModePreferred: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetAirPortJoinModeRanked"]
    pub static mut kSCValNetAirPortJoinModeRanked: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetAirPortJoinModeRecent"]
    pub static mut kSCValNetAirPortJoinModeRecent: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetAirPortJoinModeStrongest"]
    pub static mut kSCValNetAirPortJoinModeStrongest: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetAirPortAuthPasswordEncryptionKeychain"]
    pub static mut kSCValNetAirPortAuthPasswordEncryptionKeychain: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSDomainName"]
    pub static mut kSCPropNetDNSDomainName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSOptions"]
    pub static mut kSCPropNetDNSOptions: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSSearchDomains"]
    pub static mut kSCPropNetDNSSearchDomains: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSSearchOrder"]
    pub static mut kSCPropNetDNSSearchOrder: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSServerAddresses"]
    pub static mut kSCPropNetDNSServerAddresses: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSServerPort"]
    pub static mut kSCPropNetDNSServerPort: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSServerTimeout"]
    pub static mut kSCPropNetDNSServerTimeout: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSSortList"]
    pub static mut kSCPropNetDNSSortList: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSSupplementalMatchDomains"]
    pub static mut kSCPropNetDNSSupplementalMatchDomains: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetDNSSupplementalMatchOrders"]
    pub static mut kSCPropNetDNSSupplementalMatchOrders: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetEthernetMediaSubType"]
    pub static mut kSCPropNetEthernetMediaSubType: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetEthernetMediaOptions"]
    pub static mut kSCPropNetEthernetMediaOptions: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetEthernetMTU"]
    pub static mut kSCPropNetEthernetMTU: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetInterfaceDeviceName"]
    pub static mut kSCPropNetInterfaceDeviceName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetInterfaceHardware"]
    pub static mut kSCPropNetInterfaceHardware: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetInterfaceType"]
    pub static mut kSCPropNetInterfaceType: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetInterfaceSubType"]
    pub static mut kSCPropNetInterfaceSubType: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetInterfaceSupportsModemOnHold"]
    pub static mut kSCPropNetInterfaceSupportsModemOnHold: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceTypeEthernet"]
    pub static mut kSCValNetInterfaceTypeEthernet: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceTypeFireWire"]
    pub static mut kSCValNetInterfaceTypeFireWire: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceTypePPP"]
    pub static mut kSCValNetInterfaceTypePPP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceType6to4"]
    pub static mut kSCValNetInterfaceType6to4: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceTypeIPSec"]
    pub static mut kSCValNetInterfaceTypeIPSec: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceSubTypePPPoE"]
    pub static mut kSCValNetInterfaceSubTypePPPoE: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceSubTypePPPSerial"]
    pub static mut kSCValNetInterfaceSubTypePPPSerial: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceSubTypePPTP"]
    pub static mut kSCValNetInterfaceSubTypePPTP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetInterfaceSubTypeL2TP"]
    pub static mut kSCValNetInterfaceSubTypeL2TP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecAuthenticationMethod"]
    pub static mut kSCPropNetIPSecAuthenticationMethod: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecLocalCertificate"]
    pub static mut kSCPropNetIPSecLocalCertificate: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecLocalIdentifier"]
    pub static mut kSCPropNetIPSecLocalIdentifier: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecLocalIdentifierType"]
    pub static mut kSCPropNetIPSecLocalIdentifierType: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecSharedSecret"]
    pub static mut kSCPropNetIPSecSharedSecret: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecSharedSecretEncryption"]
    pub static mut kSCPropNetIPSecSharedSecretEncryption: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecConnectTime"]
    pub static mut kSCPropNetIPSecConnectTime: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecRemoteAddress"]
    pub static mut kSCPropNetIPSecRemoteAddress: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecStatus"]
    pub static mut kSCPropNetIPSecStatus: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecXAuthEnabled"]
    pub static mut kSCPropNetIPSecXAuthEnabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecXAuthName"]
    pub static mut kSCPropNetIPSecXAuthName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecXAuthPassword"]
    pub static mut kSCPropNetIPSecXAuthPassword: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPSecXAuthPasswordEncryption"]
    pub static mut kSCPropNetIPSecXAuthPasswordEncryption: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPSecAuthenticationMethodSharedSecret"]
    pub static mut kSCValNetIPSecAuthenticationMethodSharedSecret: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPSecAuthenticationMethodCertificate"]
    pub static mut kSCValNetIPSecAuthenticationMethodCertificate: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPSecAuthenticationMethodHybrid"]
    pub static mut kSCValNetIPSecAuthenticationMethodHybrid: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPSecLocalIdentifierTypeKeyID"]
    pub static mut kSCValNetIPSecLocalIdentifierTypeKeyID: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPSecSharedSecretEncryptionKeychain"]
    pub static mut kSCValNetIPSecSharedSecretEncryptionKeychain: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPSecXAuthPasswordEncryptionKeychain"]
    pub static mut kSCValNetIPSecXAuthPasswordEncryptionKeychain: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPSecXAuthPasswordEncryptionPrompt"]
    pub static mut kSCValNetIPSecXAuthPasswordEncryptionPrompt: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv4Addresses"]
    pub static mut kSCPropNetIPv4Addresses: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv4ConfigMethod"]
    pub static mut kSCPropNetIPv4ConfigMethod: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv4DHCPClientID"]
    pub static mut kSCPropNetIPv4DHCPClientID: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv4Router"]
    pub static mut kSCPropNetIPv4Router: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv4SubnetMasks"]
    pub static mut kSCPropNetIPv4SubnetMasks: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv4DestAddresses"]
    pub static mut kSCPropNetIPv4DestAddresses: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv4BroadcastAddresses"]
    pub static mut kSCPropNetIPv4BroadcastAddresses: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv4ConfigMethodAutomatic"]
    pub static mut kSCValNetIPv4ConfigMethodAutomatic: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv4ConfigMethodBOOTP"]
    pub static mut kSCValNetIPv4ConfigMethodBOOTP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv4ConfigMethodDHCP"]
    pub static mut kSCValNetIPv4ConfigMethodDHCP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv4ConfigMethodINFORM"]
    pub static mut kSCValNetIPv4ConfigMethodINFORM: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv4ConfigMethodLinkLocal"]
    pub static mut kSCValNetIPv4ConfigMethodLinkLocal: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv4ConfigMethodManual"]
    pub static mut kSCValNetIPv4ConfigMethodManual: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv4ConfigMethodPPP"]
    pub static mut kSCValNetIPv4ConfigMethodPPP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv6Addresses"]
    pub static mut kSCPropNetIPv6Addresses: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv6ConfigMethod"]
    pub static mut kSCPropNetIPv6ConfigMethod: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv6DestAddresses"]
    pub static mut kSCPropNetIPv6DestAddresses: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv6Flags"]
    pub static mut kSCPropNetIPv6Flags: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv6PrefixLength"]
    pub static mut kSCPropNetIPv6PrefixLength: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetIPv6Router"]
    pub static mut kSCPropNetIPv6Router: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv6ConfigMethodAutomatic"]
    pub static mut kSCValNetIPv6ConfigMethodAutomatic: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv6ConfigMethodLinkLocal"]
    pub static mut kSCValNetIPv6ConfigMethodLinkLocal: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv6ConfigMethodManual"]
    pub static mut kSCValNetIPv6ConfigMethodManual: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv6ConfigMethodRouterAdvertisement"]
    pub static mut kSCValNetIPv6ConfigMethodRouterAdvertisement: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetIPv6ConfigMethod6to4"]
    pub static mut kSCValNetIPv6ConfigMethod6to4: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNet6to4Relay"]
    pub static mut kSCPropNet6to4Relay: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetLinkActive"]
    pub static mut kSCPropNetLinkActive: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetLinkDetaching"]
    pub static mut kSCPropNetLinkDetaching: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemAccessPointName"]
    pub static mut kSCPropNetModemAccessPointName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemConnectionPersonality"]
    pub static mut kSCPropNetModemConnectionPersonality: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemConnectionScript"]
    pub static mut kSCPropNetModemConnectionScript: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemConnectSpeed"]
    pub static mut kSCPropNetModemConnectSpeed: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemDataCompression"]
    pub static mut kSCPropNetModemDataCompression: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemDeviceContextID"]
    pub static mut kSCPropNetModemDeviceContextID: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemDeviceModel"]
    pub static mut kSCPropNetModemDeviceModel: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemDeviceVendor"]
    pub static mut kSCPropNetModemDeviceVendor: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemDialMode"]
    pub static mut kSCPropNetModemDialMode: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemErrorCorrection"]
    pub static mut kSCPropNetModemErrorCorrection: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemHoldCallWaitingAudibleAlert"]
    pub static mut kSCPropNetModemHoldCallWaitingAudibleAlert: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemHoldDisconnectOnAnswer"]
    pub static mut kSCPropNetModemHoldDisconnectOnAnswer: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemHoldEnabled"]
    pub static mut kSCPropNetModemHoldEnabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemHoldReminder"]
    pub static mut kSCPropNetModemHoldReminder: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemHoldReminderTime"]
    pub static mut kSCPropNetModemHoldReminderTime: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemNote"]
    pub static mut kSCPropNetModemNote: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemPulseDial"]
    pub static mut kSCPropNetModemPulseDial: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemSpeaker"]
    pub static mut kSCPropNetModemSpeaker: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetModemSpeed"]
    pub static mut kSCPropNetModemSpeed: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetModemDialModeIgnoreDialTone"]
    pub static mut kSCValNetModemDialModeIgnoreDialTone: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetModemDialModeManual"]
    pub static mut kSCValNetModemDialModeManual: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetModemDialModeWaitForDialTone"]
    pub static mut kSCValNetModemDialModeWaitForDialTone: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPACSPEnabled"]
    pub static mut kSCPropNetPPPACSPEnabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPConnectTime"]
    pub static mut kSCPropNetPPPConnectTime: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPDeviceLastCause"]
    pub static mut kSCPropNetPPPDeviceLastCause: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPDialOnDemand"]
    pub static mut kSCPropNetPPPDialOnDemand: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPDisconnectOnFastUserSwitch"]
    pub static mut kSCPropNetPPPDisconnectOnFastUserSwitch: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPDisconnectOnIdle"]
    pub static mut kSCPropNetPPPDisconnectOnIdle: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPDisconnectOnIdleTimer"]
    pub static mut kSCPropNetPPPDisconnectOnIdleTimer: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPDisconnectOnLogout"]
    pub static mut kSCPropNetPPPDisconnectOnLogout: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPDisconnectOnSleep"]
    pub static mut kSCPropNetPPPDisconnectOnSleep: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPDisconnectTime"]
    pub static mut kSCPropNetPPPDisconnectTime: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPIdleReminderTimer"]
    pub static mut kSCPropNetPPPIdleReminderTimer: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPIdleReminder"]
    pub static mut kSCPropNetPPPIdleReminder: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLastCause"]
    pub static mut kSCPropNetPPPLastCause: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLogfile"]
    pub static mut kSCPropNetPPPLogfile: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPPlugins"]
    pub static mut kSCPropNetPPPPlugins: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPRetryConnectTime"]
    pub static mut kSCPropNetPPPRetryConnectTime: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPSessionTimer"]
    pub static mut kSCPropNetPPPSessionTimer: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPStatus"]
    pub static mut kSCPropNetPPPStatus: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPUseSessionTimer"]
    pub static mut kSCPropNetPPPUseSessionTimer: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPVerboseLogging"]
    pub static mut kSCPropNetPPPVerboseLogging: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPAuthEAPPlugins"]
    pub static mut kSCPropNetPPPAuthEAPPlugins: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPAuthName"]
    pub static mut kSCPropNetPPPAuthName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPAuthPassword"]
    pub static mut kSCPropNetPPPAuthPassword: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPAuthPasswordEncryption"]
    pub static mut kSCPropNetPPPAuthPasswordEncryption: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPAuthPrompt"]
    pub static mut kSCPropNetPPPAuthPrompt: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPAuthProtocol"]
    pub static mut kSCPropNetPPPAuthProtocol: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthPasswordEncryptionKeychain"]
    pub static mut kSCValNetPPPAuthPasswordEncryptionKeychain: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthPasswordEncryptionToken"]
    pub static mut kSCValNetPPPAuthPasswordEncryptionToken: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthPromptBefore"]
    pub static mut kSCValNetPPPAuthPromptBefore: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthPromptAfter"]
    pub static mut kSCValNetPPPAuthPromptAfter: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthProtocolCHAP"]
    pub static mut kSCValNetPPPAuthProtocolCHAP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthProtocolEAP"]
    pub static mut kSCValNetPPPAuthProtocolEAP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthProtocolMSCHAP1"]
    pub static mut kSCValNetPPPAuthProtocolMSCHAP1: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthProtocolMSCHAP2"]
    pub static mut kSCValNetPPPAuthProtocolMSCHAP2: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetPPPAuthProtocolPAP"]
    pub static mut kSCValNetPPPAuthProtocolPAP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommAlternateRemoteAddress"]
    pub static mut kSCPropNetPPPCommAlternateRemoteAddress: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommConnectDelay"]
    pub static mut kSCPropNetPPPCommConnectDelay: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommDisplayTerminalWindow"]
    pub static mut kSCPropNetPPPCommDisplayTerminalWindow: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommRedialCount"]
    pub static mut kSCPropNetPPPCommRedialCount: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommRedialEnabled"]
    pub static mut kSCPropNetPPPCommRedialEnabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommRedialInterval"]
    pub static mut kSCPropNetPPPCommRedialInterval: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommRemoteAddress"]
    pub static mut kSCPropNetPPPCommRemoteAddress: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommTerminalScript"]
    pub static mut kSCPropNetPPPCommTerminalScript: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCommUseTerminalScript"]
    pub static mut kSCPropNetPPPCommUseTerminalScript: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCCPEnabled"]
    pub static mut kSCPropNetPPPCCPEnabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCCPMPPE40Enabled"]
    pub static mut kSCPropNetPPPCCPMPPE40Enabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPCCPMPPE128Enabled"]
    pub static mut kSCPropNetPPPCCPMPPE128Enabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPIPCPCompressionVJ"]
    pub static mut kSCPropNetPPPIPCPCompressionVJ: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPIPCPUsePeerDNS"]
    pub static mut kSCPropNetPPPIPCPUsePeerDNS: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPEchoEnabled"]
    pub static mut kSCPropNetPPPLCPEchoEnabled: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPEchoFailure"]
    pub static mut kSCPropNetPPPLCPEchoFailure: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPEchoInterval"]
    pub static mut kSCPropNetPPPLCPEchoInterval: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPCompressionACField"]
    pub static mut kSCPropNetPPPLCPCompressionACField: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPCompressionPField"]
    pub static mut kSCPropNetPPPLCPCompressionPField: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPMRU"]
    pub static mut kSCPropNetPPPLCPMRU: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPMTU"]
    pub static mut kSCPropNetPPPLCPMTU: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPReceiveACCM"]
    pub static mut kSCPropNetPPPLCPReceiveACCM: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetPPPLCPTransmitACCM"]
    pub static mut kSCPropNetPPPLCPTransmitACCM: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetL2TPIPSecSharedSecret"]
    pub static mut kSCPropNetL2TPIPSecSharedSecret: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetL2TPIPSecSharedSecretEncryption"]
    pub static mut kSCPropNetL2TPIPSecSharedSecretEncryption: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetL2TPTransport"]
    pub static mut kSCPropNetL2TPTransport: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetL2TPIPSecSharedSecretEncryptionKeychain"]
    pub static mut kSCValNetL2TPIPSecSharedSecretEncryptionKeychain: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetL2TPTransportIP"]
    pub static mut kSCValNetL2TPTransportIP: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetL2TPTransportIPSec"]
    pub static mut kSCValNetL2TPTransportIPSec: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesExceptionsList"]
    pub static mut kSCPropNetProxiesExceptionsList: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesExcludeSimpleHostnames"]
    pub static mut kSCPropNetProxiesExcludeSimpleHostnames: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesFTPEnable"]
    pub static mut kSCPropNetProxiesFTPEnable: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesFTPPassive"]
    pub static mut kSCPropNetProxiesFTPPassive: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesFTPPort"]
    pub static mut kSCPropNetProxiesFTPPort: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesFTPProxy"]
    pub static mut kSCPropNetProxiesFTPProxy: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesGopherEnable"]
    pub static mut kSCPropNetProxiesGopherEnable: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesGopherPort"]
    pub static mut kSCPropNetProxiesGopherPort: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesGopherProxy"]
    pub static mut kSCPropNetProxiesGopherProxy: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesHTTPEnable"]
    pub static mut kSCPropNetProxiesHTTPEnable: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesHTTPPort"]
    pub static mut kSCPropNetProxiesHTTPPort: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesHTTPProxy"]
    pub static mut kSCPropNetProxiesHTTPProxy: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesHTTPSEnable"]
    pub static mut kSCPropNetProxiesHTTPSEnable: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesHTTPSPort"]
    pub static mut kSCPropNetProxiesHTTPSPort: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesHTTPSProxy"]
    pub static mut kSCPropNetProxiesHTTPSProxy: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesRTSPEnable"]
    pub static mut kSCPropNetProxiesRTSPEnable: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesRTSPPort"]
    pub static mut kSCPropNetProxiesRTSPPort: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesRTSPProxy"]
    pub static mut kSCPropNetProxiesRTSPProxy: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesSOCKSEnable"]
    pub static mut kSCPropNetProxiesSOCKSEnable: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesSOCKSPort"]
    pub static mut kSCPropNetProxiesSOCKSPort: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesSOCKSProxy"]
    pub static mut kSCPropNetProxiesSOCKSProxy: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesProxyAutoConfigEnable"]
    pub static mut kSCPropNetProxiesProxyAutoConfigEnable: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesProxyAutoConfigJavaScript"]
    pub static mut kSCPropNetProxiesProxyAutoConfigJavaScript: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesProxyAutoConfigURLString"]
    pub static mut kSCPropNetProxiesProxyAutoConfigURLString: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetProxiesProxyAutoDiscoveryEnable"]
    pub static mut kSCPropNetProxiesProxyAutoDiscoveryEnable: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetSMBNetBIOSName"]
    pub static mut kSCPropNetSMBNetBIOSName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetSMBNetBIOSNodeType"]
    pub static mut kSCPropNetSMBNetBIOSNodeType: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetSMBNetBIOSScope"]
    pub static mut kSCPropNetSMBNetBIOSScope: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetSMBWINSAddresses"]
    pub static mut kSCPropNetSMBWINSAddresses: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropNetSMBWorkgroup"]
    pub static mut kSCPropNetSMBWorkgroup: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetSMBNetBIOSNodeTypeBroadcast"]
    pub static mut kSCValNetSMBNetBIOSNodeTypeBroadcast: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetSMBNetBIOSNodeTypePeer"]
    pub static mut kSCValNetSMBNetBIOSNodeTypePeer: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetSMBNetBIOSNodeTypeMixed"]
    pub static mut kSCValNetSMBNetBIOSNodeTypeMixed: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCValNetSMBNetBIOSNodeTypeHybrid"]
    pub static mut kSCValNetSMBNetBIOSNodeTypeHybrid: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCEntUsersConsoleUser"]
    pub static mut kSCEntUsersConsoleUser: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropSystemComputerName"]
    pub static mut kSCPropSystemComputerName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropSystemComputerNameEncoding"]
    pub static mut kSCPropSystemComputerNameEncoding: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStoreDomainFile"]
    pub static mut kSCDynamicStoreDomainFile: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStoreDomainPlugin"]
    pub static mut kSCDynamicStoreDomainPlugin: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStoreDomainSetup"]
    pub static mut kSCDynamicStoreDomainSetup: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStoreDomainState"]
    pub static mut kSCDynamicStoreDomainState: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStoreDomainPrefs"]
    pub static mut kSCDynamicStoreDomainPrefs: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStorePropSetupCurrentSet"]
    pub static mut kSCDynamicStorePropSetupCurrentSet: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStorePropSetupLastUpdated"]
    pub static mut kSCDynamicStorePropSetupLastUpdated: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStorePropNetInterfaces"]
    pub static mut kSCDynamicStorePropNetInterfaces: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStorePropNetPrimaryInterface"]
    pub static mut kSCDynamicStorePropNetPrimaryInterface: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStorePropNetPrimaryService"]
    pub static mut kSCDynamicStorePropNetPrimaryService: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCDynamicStorePropNetServiceIDs"]
    pub static mut kSCDynamicStorePropNetServiceIDs: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropUsersConsoleUserName"]
    pub static mut kSCPropUsersConsoleUserName: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropUsersConsoleUserUID"]
    pub static mut kSCPropUsersConsoleUserUID: CFStringRef;
}
extern "C" {
    #[link_name = "\u{1}_kSCPropUsersConsoleUserGID"]
    pub static mut kSCPropUsersConsoleUserGID: CFStringRef;
}
