/* automatically generated by rust-bindgen */

// Generated using:
// bindgen 0.51.0
// macOS SDK 10.14.

use core_foundation_sys::string::CFStringRef;

extern "C" {
    pub static kSCResvLink: CFStringRef;
}
extern "C" {
    pub static kSCResvInactive: CFStringRef;
}
extern "C" {
    pub static kSCPropInterfaceName: CFStringRef;
}
extern "C" {
    pub static kSCPropMACAddress: CFStringRef;
}
extern "C" {
    pub static kSCPropUserDefinedName: CFStringRef;
}
extern "C" {
    pub static kSCPropVersion: CFStringRef;
}
extern "C" {
    pub static kSCPrefCurrentSet: CFStringRef;
}
extern "C" {
    pub static kSCPrefNetworkServices: CFStringRef;
}
extern "C" {
    pub static kSCPrefSets: CFStringRef;
}
extern "C" {
    pub static kSCPrefSystem: CFStringRef;
}
extern "C" {
    pub static kSCCompNetwork: CFStringRef;
}
extern "C" {
    pub static kSCCompService: CFStringRef;
}
extern "C" {
    pub static kSCCompGlobal: CFStringRef;
}
extern "C" {
    pub static kSCCompHostNames: CFStringRef;
}
extern "C" {
    pub static kSCCompInterface: CFStringRef;
}
extern "C" {
    pub static kSCCompSystem: CFStringRef;
}
extern "C" {
    pub static kSCCompUsers: CFStringRef;
}
extern "C" {
    pub static kSCCompAnyRegex: CFStringRef;
}
extern "C" {
    pub static kSCEntNetAirPort: CFStringRef;
}
extern "C" {
    pub static kSCEntNetDHCP: CFStringRef;
}
extern "C" {
    pub static kSCEntNetDNS: CFStringRef;
}
extern "C" {
    pub static kSCEntNetEthernet: CFStringRef;
}
extern "C" {
    pub static kSCEntNetFireWire: CFStringRef;
}
extern "C" {
    pub static kSCEntNetInterface: CFStringRef;
}
extern "C" {
    pub static kSCEntNetIPSec: CFStringRef;
}
extern "C" {
    pub static kSCEntNetIPv4: CFStringRef;
}
extern "C" {
    pub static kSCEntNetIPv6: CFStringRef;
}
extern "C" {
    pub static kSCEntNetL2TP: CFStringRef;
}
extern "C" {
    pub static kSCEntNetLink: CFStringRef;
}
extern "C" {
    pub static kSCEntNetModem: CFStringRef;
}
extern "C" {
    pub static kSCEntNetPPP: CFStringRef;
}
extern "C" {
    pub static kSCEntNetPPPoE: CFStringRef;
}
extern "C" {
    pub static kSCEntNetPPPSerial: CFStringRef;
}
extern "C" {
    pub static kSCEntNetPPTP: CFStringRef;
}
extern "C" {
    pub static kSCEntNetProxies: CFStringRef;
}
extern "C" {
    pub static kSCEntNetSMB: CFStringRef;
}
extern "C" {
    pub static kSCEntNet6to4: CFStringRef;
}
extern "C" {
    pub static kSCPropNetOverridePrimary: CFStringRef;
}
extern "C" {
    pub static kSCPropNetServiceOrder: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPOverridePrimary: CFStringRef;
}
extern "C" {
    pub static kSCPropNetInterfaces: CFStringRef;
}
extern "C" {
    pub static kSCPropNetLocalHostName: CFStringRef;
}
extern "C" {
    pub static kSCPropNetAirPortAllowNetCreation: CFStringRef;
}
extern "C" {
    pub static kSCPropNetAirPortAuthPassword: CFStringRef;
}
extern "C" {
    pub static kSCPropNetAirPortAuthPasswordEncryption: CFStringRef;
}
extern "C" {
    pub static kSCPropNetAirPortJoinMode: CFStringRef;
}
extern "C" {
    pub static kSCPropNetAirPortPowerEnabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetAirPortPreferredNetwork: CFStringRef;
}
extern "C" {
    pub static kSCPropNetAirPortSavePasswords: CFStringRef;
}
extern "C" {
    pub static kSCValNetAirPortJoinModeAutomatic: CFStringRef;
}
extern "C" {
    pub static kSCValNetAirPortJoinModePreferred: CFStringRef;
}
extern "C" {
    pub static kSCValNetAirPortJoinModeRanked: CFStringRef;
}
extern "C" {
    pub static kSCValNetAirPortJoinModeRecent: CFStringRef;
}
extern "C" {
    pub static kSCValNetAirPortJoinModeStrongest: CFStringRef;
}
extern "C" {
    pub static kSCValNetAirPortAuthPasswordEncryptionKeychain: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSDomainName: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSOptions: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSSearchDomains: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSSearchOrder: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSServerAddresses: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSServerPort: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSServerTimeout: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSSortList: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSSupplementalMatchDomains: CFStringRef;
}
extern "C" {
    pub static kSCPropNetDNSSupplementalMatchOrders: CFStringRef;
}
extern "C" {
    pub static kSCPropNetEthernetMediaSubType: CFStringRef;
}
extern "C" {
    pub static kSCPropNetEthernetMediaOptions: CFStringRef;
}
extern "C" {
    pub static kSCPropNetEthernetMTU: CFStringRef;
}
extern "C" {
    pub static kSCPropNetInterfaceDeviceName: CFStringRef;
}
extern "C" {
    pub static kSCPropNetInterfaceHardware: CFStringRef;
}
extern "C" {
    pub static kSCPropNetInterfaceType: CFStringRef;
}
extern "C" {
    pub static kSCPropNetInterfaceSubType: CFStringRef;
}
extern "C" {
    pub static kSCPropNetInterfaceSupportsModemOnHold: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceTypeEthernet: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceTypeFireWire: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceTypePPP: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceType6to4: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceTypeIPSec: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceSubTypePPPoE: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceSubTypePPPSerial: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceSubTypePPTP: CFStringRef;
}
extern "C" {
    pub static kSCValNetInterfaceSubTypeL2TP: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecAuthenticationMethod: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecLocalCertificate: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecLocalIdentifier: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecLocalIdentifierType: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecSharedSecret: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecSharedSecretEncryption: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecConnectTime: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecRemoteAddress: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecStatus: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecXAuthEnabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecXAuthName: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecXAuthPassword: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPSecXAuthPasswordEncryption: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPSecAuthenticationMethodSharedSecret: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPSecAuthenticationMethodCertificate: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPSecAuthenticationMethodHybrid: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPSecLocalIdentifierTypeKeyID: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPSecSharedSecretEncryptionKeychain: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPSecXAuthPasswordEncryptionKeychain: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPSecXAuthPasswordEncryptionPrompt: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv4Addresses: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv4ConfigMethod: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv4DHCPClientID: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv4Router: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv4SubnetMasks: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv4DestAddresses: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv4BroadcastAddresses: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv4ConfigMethodAutomatic: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv4ConfigMethodBOOTP: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv4ConfigMethodDHCP: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv4ConfigMethodINFORM: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv4ConfigMethodLinkLocal: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv4ConfigMethodManual: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv4ConfigMethodPPP: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv6Addresses: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv6ConfigMethod: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv6DestAddresses: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv6Flags: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv6PrefixLength: CFStringRef;
}
extern "C" {
    pub static kSCPropNetIPv6Router: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv6ConfigMethodAutomatic: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv6ConfigMethodLinkLocal: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv6ConfigMethodManual: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv6ConfigMethodRouterAdvertisement: CFStringRef;
}
extern "C" {
    pub static kSCValNetIPv6ConfigMethod6to4: CFStringRef;
}
extern "C" {
    pub static kSCPropNet6to4Relay: CFStringRef;
}
extern "C" {
    pub static kSCPropNetLinkActive: CFStringRef;
}
extern "C" {
    pub static kSCPropNetLinkDetaching: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemAccessPointName: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemConnectionPersonality: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemConnectionScript: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemConnectSpeed: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemDataCompression: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemDeviceContextID: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemDeviceModel: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemDeviceVendor: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemDialMode: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemErrorCorrection: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemHoldCallWaitingAudibleAlert: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemHoldDisconnectOnAnswer: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemHoldEnabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemHoldReminder: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemHoldReminderTime: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemNote: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemPulseDial: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemSpeaker: CFStringRef;
}
extern "C" {
    pub static kSCPropNetModemSpeed: CFStringRef;
}
extern "C" {
    pub static kSCValNetModemDialModeIgnoreDialTone: CFStringRef;
}
extern "C" {
    pub static kSCValNetModemDialModeManual: CFStringRef;
}
extern "C" {
    pub static kSCValNetModemDialModeWaitForDialTone: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPACSPEnabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPConnectTime: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPDeviceLastCause: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPDialOnDemand: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPDisconnectOnFastUserSwitch: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPDisconnectOnIdle: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPDisconnectOnIdleTimer: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPDisconnectOnLogout: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPDisconnectOnSleep: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPDisconnectTime: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPIdleReminderTimer: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPIdleReminder: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLastCause: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLogfile: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPPlugins: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPRetryConnectTime: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPSessionTimer: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPStatus: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPUseSessionTimer: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPVerboseLogging: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPAuthEAPPlugins: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPAuthName: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPAuthPassword: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPAuthPasswordEncryption: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPAuthPrompt: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPAuthProtocol: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthPasswordEncryptionKeychain: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthPasswordEncryptionToken: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthPromptBefore: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthPromptAfter: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthProtocolCHAP: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthProtocolEAP: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthProtocolMSCHAP1: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthProtocolMSCHAP2: CFStringRef;
}
extern "C" {
    pub static kSCValNetPPPAuthProtocolPAP: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommAlternateRemoteAddress: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommConnectDelay: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommDisplayTerminalWindow: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommRedialCount: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommRedialEnabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommRedialInterval: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommRemoteAddress: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommTerminalScript: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCommUseTerminalScript: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCCPEnabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCCPMPPE40Enabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPCCPMPPE128Enabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPIPCPCompressionVJ: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPIPCPUsePeerDNS: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPEchoEnabled: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPEchoFailure: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPEchoInterval: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPCompressionACField: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPCompressionPField: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPMRU: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPMTU: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPReceiveACCM: CFStringRef;
}
extern "C" {
    pub static kSCPropNetPPPLCPTransmitACCM: CFStringRef;
}
extern "C" {
    pub static kSCPropNetL2TPIPSecSharedSecret: CFStringRef;
}
extern "C" {
    pub static kSCPropNetL2TPIPSecSharedSecretEncryption: CFStringRef;
}
extern "C" {
    pub static kSCPropNetL2TPTransport: CFStringRef;
}
extern "C" {
    pub static kSCValNetL2TPIPSecSharedSecretEncryptionKeychain: CFStringRef;
}
extern "C" {
    pub static kSCValNetL2TPTransportIP: CFStringRef;
}
extern "C" {
    pub static kSCValNetL2TPTransportIPSec: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesExceptionsList: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesExcludeSimpleHostnames: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesFTPEnable: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesFTPPassive: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesFTPPort: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesFTPProxy: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesGopherEnable: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesGopherPort: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesGopherProxy: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesHTTPEnable: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesHTTPPort: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesHTTPProxy: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesHTTPSEnable: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesHTTPSPort: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesHTTPSProxy: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesRTSPEnable: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesRTSPPort: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesRTSPProxy: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesSOCKSEnable: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesSOCKSPort: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesSOCKSProxy: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesProxyAutoConfigEnable: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesProxyAutoConfigJavaScript: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesProxyAutoConfigURLString: CFStringRef;
}
extern "C" {
    pub static kSCPropNetProxiesProxyAutoDiscoveryEnable: CFStringRef;
}
extern "C" {
    pub static kSCPropNetSMBNetBIOSName: CFStringRef;
}
extern "C" {
    pub static kSCPropNetSMBNetBIOSNodeType: CFStringRef;
}
extern "C" {
    pub static kSCPropNetSMBNetBIOSScope: CFStringRef;
}
extern "C" {
    pub static kSCPropNetSMBWINSAddresses: CFStringRef;
}
extern "C" {
    pub static kSCPropNetSMBWorkgroup: CFStringRef;
}
extern "C" {
    pub static kSCValNetSMBNetBIOSNodeTypeBroadcast: CFStringRef;
}
extern "C" {
    pub static kSCValNetSMBNetBIOSNodeTypePeer: CFStringRef;
}
extern "C" {
    pub static kSCValNetSMBNetBIOSNodeTypeMixed: CFStringRef;
}
extern "C" {
    pub static kSCValNetSMBNetBIOSNodeTypeHybrid: CFStringRef;
}
extern "C" {
    pub static kSCEntUsersConsoleUser: CFStringRef;
}
extern "C" {
    pub static kSCPropSystemComputerName: CFStringRef;
}
extern "C" {
    pub static kSCPropSystemComputerNameEncoding: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStoreDomainFile: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStoreDomainPlugin: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStoreDomainSetup: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStoreDomainState: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStoreDomainPrefs: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStorePropSetupCurrentSet: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStorePropSetupLastUpdated: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStorePropNetInterfaces: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStorePropNetPrimaryInterface: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStorePropNetPrimaryService: CFStringRef;
}
extern "C" {
    pub static kSCDynamicStorePropNetServiceIDs: CFStringRef;
}
extern "C" {
    pub static kSCPropUsersConsoleUserName: CFStringRef;
}
extern "C" {
    pub static kSCPropUsersConsoleUserUID: CFStringRef;
}
extern "C" {
    pub static kSCPropUsersConsoleUserGID: CFStringRef;
}
