/* automatically generated by rust-bindgen 0.70.1 */

// Generated using:
// bindgen 0.70.1
// macOS SDK 14.5.

use core_foundation_sys::error::CFErrorRef;
use core_foundation_sys::string::CFStringRef;

pub const kSCStatusOK: _bindgen_ty_64 = 0;
pub const kSCStatusFailed: _bindgen_ty_64 = 1001;
pub const kSCStatusInvalidArgument: _bindgen_ty_64 = 1002;
pub const kSCStatusAccessError: _bindgen_ty_64 = 1003;
pub const kSCStatusNoKey: _bindgen_ty_64 = 1004;
pub const kSCStatusKeyExists: _bindgen_ty_64 = 1005;
pub const kSCStatusLocked: _bindgen_ty_64 = 1006;
pub const kSCStatusNeedLock: _bindgen_ty_64 = 1007;
pub const kSCStatusNoStoreSession: _bindgen_ty_64 = 2001;
pub const kSCStatusNoStoreServer: _bindgen_ty_64 = 2002;
pub const kSCStatusNotifierActive: _bindgen_ty_64 = 2003;
pub const kSCStatusNoPrefsSession: _bindgen_ty_64 = 3001;
pub const kSCStatusPrefsBusy: _bindgen_ty_64 = 3002;
pub const kSCStatusNoConfigFile: _bindgen_ty_64 = 3003;
pub const kSCStatusNoLink: _bindgen_ty_64 = 3004;
pub const kSCStatusStale: _bindgen_ty_64 = 3005;
pub const kSCStatusMaxLink: _bindgen_ty_64 = 3006;
pub const kSCStatusReachabilityUnknown: _bindgen_ty_64 = 4001;
pub const kSCStatusConnectionNoService: _bindgen_ty_64 = 5001;
pub const kSCStatusConnectionIgnore: _bindgen_ty_64 = 5002;
pub type _bindgen_ty_64 = ::core::ffi::c_uint;
extern "C" {
    pub static kCFErrorDomainSystemConfiguration: CFStringRef;

    pub fn SCCopyLastError() -> CFErrorRef;

    pub fn SCError() -> ::core::ffi::c_int;

    pub fn SCErrorString(status: ::core::ffi::c_int) -> *const ::core::ffi::c_char;
}
