language: rust
cache: cargo
rust:
  - 1.31.0
  - nightly
  - stable
  - beta
os:
  - osx

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  - if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then
      if rustup component add rustfmt-preview; then
        rustfmt --version;
        cargo fmt -- --check --unstable-features;
      else
        echo "rustfmt not available in this nightly";
      fi
    else
      echo "Not checking formatting on this build";
    fi
  - if rustup component add clippy; then
      cargo clippy --all-targets -- --deny warnings;
    fi


notifications:
  email:
    on_success: never
    on_failure: never
